In [ ]:
# milage of each car
kms = [153.4, 123.4, 113.5, 118.4]
# grams of emissions per km
emissions = {"CO2": 120.4, "N2O":0.005, "CH4":0.25}
for km in kms:
  for gas, grams in emissions.items():
    print("Total emissions of " + gas + " are: " + str(km*grams) + "grams")

Total emissions of CO2 are: 18469.36grams
Total emissions of N2O are: 0.767grams
Total emissions of CH4 are: 38.35grams
Total emissions of CO2 are: 14857.36grams
Total emissions of N2O are: 0.617grams
Total emissions of CH4 are: 30.85grams
Total emissions of CO2 are: 14857.36grams
Total emissions of N2O are: 0.617grams
Total emissions of CH4 are: 30.85grams
Total emissions of CO2 are: 14857.36grams
Total emissions of N2O are: 0.617grams
Total emissions of CH4 are: 30.85grams


In [ ]:
# milage of each car
import numpy as np

kms = np.array([[153.4], [123.4], [113.5], [118.4]])
emissions = np.array([[120.4, 0.005, 0.25]])
values = kms@emissions
print(values)
print(values.shape)
print(values.size)


[[1.846936e+04 7.670000e-01 3.835000e+01]
 [1.485736e+04 6.170000e-01 3.085000e+01]
 [1.366540e+04 5.675000e-01 2.837500e+01]
 [1.425536e+04 5.920000e-01 2.960000e+01]]
(4, 3)
12


In [ ]:
an_array = [1, 2, 3, 5]
another_array = [6, 7, 8, 9]
dot_product = 0
for j in range(len(an_array)):
  dot_product += an_array[j]*another_array[j]
print(dot_product)


89


In [ ]:
import numpy as np
an_array = np.array([1, 2, 3, 5])
another_array = np.array([6, 7, 8, 9])
dot_product = an_array@another_array
print(dot_product)

89


In [ ]:
a_matrix = [[1, 2, 3],[4, 5, 6]]
another_matrix = [[1, 2],[3, 4],[5, 6]]
m = len(a_matrix)
n = len(another_matrix)
p = len(another_matrix[0])
matrix_product = [ [ 0 for i in range(m) ] for j in range(p) ]
for i in range(m):
  for c in range(n):
    for j in range(p):
      matrix_product[i][j]+=a_matrix[i][c]*another_matrix[c][j]

print(matrix_product)

[[22, 28], [49, 64]]


In [ ]:
import numpy as np
a_matrix = np.array([[1, 2, 3],[4, 5, 6]])
another_matrix = np.array([[1, 2],[3, 4],[5, 6]])
matrix_product = a_matrix@another_matrix
print(matrix_product)

[[22 28]
 [49 64]]


In [ ]:
import numpy as np
mu = 110 # mean mileage
sigma = 5 # standard deviation
# 10000 random numbers with average "mu" and 
global_sales = np.random.normal(mu, sigma, (2, 5, 500, 2))
comissions = np.array([[1, 2, 3],[4, 5, 6]])
#reshape into the following axis:
# Regions
# Countries
# Sale agents
# Products

# global_sales = global_sales.reshape(2,5,500,2)
# commission rates with the following axis:
# Products
# Sale rates: (commission rate, net profit, sale price) 
rates = np.array([[0.15, 15, 25],[0.13, 13, 18]])
# for each region, country, and sale agent, calculate the total commission paid
# to each sales agents, the total net profit and the total sale revenues
print(global_sales.shape)
print(rates.shape)
sale_values = np.dot(global_sales, comissions)
print(sale_values.shape)

(2, 5, 500, 2)
(2, 3)
(2, 5, 500, 3)


In [ ]:
import numpy as np
a_matrix = np.random.randint(5, size=(4,3))
print(a_matrix.shape)
a_matrix_transposed = a_matrix.transpose()
print(a_matrix_transposed.shape)
a_multidimensional_array = np.random.randint(5, size=(2,3,5) )
# shape of multi
print(a_multidimensional_array.shape)
a_multidimensional_array_transposed = a_multidimensional_array.transpose()
print(a_multidimensional_array_transposed.shape)


(4, 3)
(3, 4)
(2, 3, 5)
(5, 3, 2)


In [ ]:
import numpy as np
an_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
a_matrix = an_array.reshape(6,2)
# a_matrix is of shape 6,2 and size 12
print(a_matrix)
a_multidimensional_array = a_matrix.reshape(3,2,2)
# a multidimensional array is of shape 3,2,2
print(a_multidimensional_array)
another_multidimensional_array = an_array.reshape(3,2,1,2)
print(another_multidimensional_array)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[[ 1  2]]

  [[ 3  4]]]


 [[[ 5  6]]

  [[ 7  8]]]


 [[[ 9 10]]

  [[11 12]]]]


In [ ]:
import numpy as np
