# Matrix Algebra

## Try me
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ffraile/computer_science_tutorials/blob/main/source/Applied%20Mathematics/tutorials/Matrix%20algebra%20with%20Numpy.ipynb)[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ffraile/computer_science_tutorials/main?labpath=source%2FApplied%20Mathematics%2Ftutorials%2FMatrix%20algebra%20with%20Numpy.ipynb)
> ☝ Important! Remember that to use Numpy in your Notebooks and programs, you first need to import the package (in this example we use the alias np):

In [ ]:
import numpy as np

## Linear algebra operations
### Dot product
You can use the standard Python matrix product operator '@' to perform the scalar product of two vectors:

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

c = a@b
print(c)

55


The ```np.dot``` function works just the same:

In [5]:
c = np.dot(a,b)
print(c)

55


## Matrix product
The same rules apply to the matrix product, the standard Python operator ```@``` or the ```np.dot``` function can be used to perform a matrix product, but the ```@``` operator is prefered:

In [8]:
A = np.array([[1, 3], [3,4]])  # this is a 2x2 matrix
b = np.array([[1], [2]])       #this is a column vector (2x1 matrix)

C = np.dot(A, b)
print(C)

C = A @ b
print(C)

[[ 7]
 [11]]
[[ 7]
 [11]]


### Transpose
The ```transpose()``` method returns the transpose:

In [10]:
A = np.array([[1, 3], [3,4], [5, 6]])  # this is a 3x2 matrix
print("A is: ")
print(A)
print("And it´s shape is:")
print(A.shape)
print("The transpose is:")
A_t = A.transpose()
print(A_t)
print("And its shape:")
print(A_t.shape)

A is: 
[[1 3]
 [3 4]
 [5 6]]
And it´s shape is:
(3, 2)
The transpose is:
[[1 3 5]
 [3 4 6]]
And its shape:
(2, 3)


### Reshape
Reshape changes the shape of a numpy array:

In [13]:
a = np.arange(1, 28) # an array with 27 elements

A = a.reshape(3,3,3) #A has the same elements but shape 3x3x3

print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
