# NumPy Basics — Class Notes

**Goal:** Learn core NumPy concepts for array programming: creation, shapes/dtypes, indexing & slicing, broadcasting, vectorized ops, aggregations.

Use the **predict → run** habit: mentally predict outputs, then execute to check.

## 0) Setup
Import NumPy (aliased as `np`).

In [1]:

import numpy as np


## 1) Creating arrays

- From Python objects: `np.array([1,2,3])`
- Ranges / grids: `np.arange`, `np.linspace`
- Filled arrays: `np.zeros`, `np.ones`, `np.full`, `np.eye`
- Random: Normal distribution `np.random.normal` (explore others)

In [ ]:

a = np.array([1, 2, 3], dtype=np.int32)
b = np.arange(0, 10, 2)           # step range
c = np.linspace(0, 1, 5)          # 5 points in [0,1]
Z = np.zeros((2,3))
O = np.ones((3,2))
F = np.full((2,2), 7.5)
I = np.eye(3)

R = np.random.normal(low=0, high=10, size=(2,3))
print("a:", a, a.dtype)
print("b:", b)
print("c:", c)
print("Z:", Z)
print("I:", I)
print("R:", R)

### 1.1 Basic Operations
- Elementwise operations: `+ - * / **`


In [12]:
A = [[1, 2, 3],
     [4, 5, 6]]

print("A:", A)
print("A + 10:", np.array(A) + 10)
print("A * 2:", np.array(A) * 2)
print("A ** 2:", np.array(A) ** 2)


A: [[1, 2, 3], [4, 5, 6]]
A + 10: [[11 12 13]
 [14 15 16]]
A * 2: [[ 2  4  6]
 [ 8 10 12]]
A ** 2: [[ 1  4  9]
 [16 25 36]]


**!Important! tips**:
- 1) assigning parts of an array to another variable does not create a copy, it creates a **view**. Changes to the view will affect the original array. Use `.copy()` or `np.array(A)` to create a true copy.
- 2) Arrays are homogeneous: all elements have the same dtype.
- 3) Using `dtype` parameter when creating arrays ensures the desired data type (optimizes memory and performance).

## 2) Shape, dtype, size

Useful attributes:
- `.shape`: Shape of the array (eg 2x3)
- `.ndim`: Number of dimensions
- `.size`: Number of elements,
- `.dtype`: Type of elements,
- `.itemsize`: Size of elements in Memory
- `astype` to convert dtype

In [ ]:

M = np.random.normal(0, 100, size=(3,4))
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size)
print("dtype:", M.dtype, "| itemsize:", M.itemsize, "bytes")
print("astype float32:", M.astype(np.float32))
print("New itemsize: ", M.astype(np.float32).itemsize, "bytes")

## 3) Indexing & slicing

- 1D arrays indexing and slicing just like lists: `x[i]`, `x[i:j:k]`
- 2D arrays: row/column index/slices: `A[i, j]`, `A[i, j1:j2]`,
- Boolean masks: `mask = (A % 2 == 0)` → `A[mask]`

In [4]:

x = np.arange(10)
A = np.random.normal(0, 20, size=(4,5))
print("x:", x)
print("x[2:8:2]:", x[2:8:2])
print("A:", A)
print("A[1, :]:", A[1, :]) # Second row
print("A[:, 2]:", A[:, 2]) # Third column


x: [0 1 2 3 4 5 6 7 8 9]
x[2:8:2]: [2 4 6]
A: [[ 28.68464535  22.33912277   7.79074057 -18.09582535   3.26603901]
 [  4.42741255 -15.85879854 -17.55995071  17.44003336  -9.42848622]
 [-11.49027909  -4.60882982   4.10650666  -5.91129897  -3.98889954]
 [ 14.21313969   7.55070982  31.37476978 -44.10618956  16.35539171]]
A[1, :]: [  4.42741255 -15.85879854 -17.55995071  17.44003336  -9.42848622]
A[:, 2]: [  7.79074057 -17.55995071   4.10650666  31.37476978]
A greater than 2: [28.68464535 22.33912277  7.79074057  3.26603901  4.42741255 17.44003336
  4.10650666 14.21313969  7.55070982 31.37476978 16.35539171]
mask: [[1 1 1 0 1]
 [1 0 0 1 0]
 [0 0 1 0 0]
 [1 1 1 0 1]]
A[mask]: [28.68464535 22.33912277  7.79074057  3.26603901  4.42741255 17.44003336
  4.10650666 14.21313969  7.55070982 31.37476978 16.35539171]


3.1) Boolean masks
Create a boolean mask and use it to filter an array.
- *Boolean mask* is an array of `True`/`False` values.


In [ ]:
# Filter data with boolean mask
print("A greater than 2:", A[A >= 2.0])

# We can store the boolean mask in a variable
mask = (A >= 2.0)
print("mask:", mask.astype(int))
print("A[mask]:", A[mask])

# Peer-Instruction Cards (NumPy Basics)

Predict first, then run the check cell (when provided).

### Card N-1 — Slicing vs copying
```python
A = np.arange(9).reshape(3,3)
B = A[0, :]      # row view or copy?
B[0] = 99
```
**Q:** Does `A` change? Which element?

In [11]:

A = np.arange(9).reshape(3,3)
B = A[0, :]
print("Before change, A:", A)
print("Before change, B:", B)
B[0] = 99
print("A:", A)  # views: A[0,0] becomes 99

A: [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]]


### Card N-2 — Fancy indexing
What is the output of:
```python
X = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(X[1, ::-1])
```


### Card N-3 — Boolean mask
```python
X = np.array([[-1,0,1],[2,-2,3]])
X[X<0] = X[X<0] + 10
```
**Q:** Predict the final `X`.

In [7]:

X = np.array([[-1,0,1],[2,-2,3]])
X[X<0] = X[X<0] + 10
print(X)

[[9 0 1]
 [2 8 3]]


### Card N-3 — Axis confusion
`np.sum(A, axis=1)` collapses which dimension? Predict result shape for `A.shape == (4,5,6)`.

In [6]:

A = np.zeros((4,5,6))
print("sum axis=1 -> shape", np.sum(A, axis=1).shape)  # (4,6)

sum axis=1 -> shape (4, 6)


## 4) Broadcasting

Broadcasting allows operations on arrays of different shapes.
**Rules:** align shapes **from the right**; dims are compatible if equal or either is `1`.

Examples: add a vector to each row/column.

In [ ]:

B = np.random.normal(0, 10, size=(3,4))
row = np.array([1, 0, -1, 2])    # row vector shape (4,)
col = np.array([[10],[20],[30]]) # column vector shape (3,1)

print("B:", B)
print("B + row:", B + row)   # broadcast across rows
print("B + col:", B + col)   # broadcast down columns

## 5) Vectorized ops & ufuncs

- Elementwise: `+ - * / **`
- Ufuncs: `np.sqrt`, `np.exp`, `np.clip`, `np.where`
- Aggregations: `np.sum`, `np.mean`, `np.std`, `axis=`

In [5]:

X = np.linspace(-2, 2, 5)
print("X:", X)
print("X**2:", X**2)
print("sqrt(abs(X)):", np.sqrt(np.abs(X)))
print("where(X>=0, 1, -1):", np.where(X>=0, 1, -1))

G = np.random.normal(loc=0, scale=1, size=(3,4))
print("G:", G)
print("sum all:", np.sum(G))
print("mean per column:", np.mean(G, axis=0))
print("std per row:", np.std(G, axis=1))

X: [-2. -1.  0.  1.  2.]
X**2: [4. 1. 0. 1. 4.]
sqrt(abs(X)): [1.41421356 1.         0.         1.         1.41421356]
where(X>=0, 1, -1): [-1 -1  1  1  1]
G: [[-0.63837677  0.95390108 -0.17377379  0.35361888]
 [ 1.11801869 -0.38510265 -0.29856934 -1.55956457]
 [ 0.16250772  0.31387611  0.04093736 -0.70591152]]
sum all: -0.8184388095951249
mean per column: [ 0.21404988  0.29422485 -0.14380192 -0.63728574]
std per row: [0.59400086 0.94909514 0.39243545]


### Quick self-checks (asserts)
Run once; no output means the checks passed.

In [ ]:

X = np.arange(6).reshape(2,3)
row = np.array([10, 20, 30])
Y = X + row
assert Y[1,2] == (3+30)

mask = (X % 2 == 0)
evens = X[mask]
assert evens.tolist() == [0,2,4]

B = np.ones((3,1)) + np.arange(4)  # broadcast to (3,4)
assert B.shape == (3,4)

### Card N-4 — Broadcasting shape
Predict the shape of `np.ones((2,1,4)) + np.ones((3,4))` (if valid).

In [10]:

try:
    out = np.ones((2,1,4)) + np.ones((3,4))
    print("ok, shape:", out.shape)
except ValueError as e:
    print("ValueError:", e)

ok, shape: (2, 3, 4)


## Mini challenges

1) Given `S` (shape `(m,n)`), subtract the column-wise mean from each column (result same shape).  
2) Standardize rows of `A` to zero-mean, unit-variance (per row).  
3) Build a 10×10 checkerboard of 0/1 using slicing (no loops).

In [ ]:

# Reference solutions
S = np.random.normal(size=(4,5))
S_centered = S - S.mean(axis=0, keepdims=True)
print("1) col-centered OK:", np.allclose(S_centered.mean(axis=0), 0, atol=1e-7))

A = np.random.normal(size=(3,6))
A0 = (A - A.mean(axis=1, keepdims=True)) / A.std(axis=1, keepdims=True)
print("2) row standardized shapes:", A0.shape)

CB = np.zeros((10,10), dtype=int)
CB[::2,1::2] = 1
CB[1::2,::2] = 1
print("3) checkerboard (top-left 3x3):", CB[:3,:3])

## Takeaways
- Think in **shapes**; read errors as shape mismatches or dtype issues.
- **Broadcast** small arrays across larger ones when dimensions are `1` or equal.
- Most operations are **vectorized**; prefer them over Python loops.
- Use `axis=` parameters to aggregate along a dimension.
- Boolean masks and fancy indexing are powerful—watch out for views vs copies.