# NumPy Basics — Class Notes

**Goal:** Learn core NumPy concepts for array programming: creation, shapes/dtypes, indexing & slicing, broadcasting, vectorized ops, aggregations.

Use the **predict → run** habit: mentally predict outputs, then execute to check.

## 0) Setup
- `import` keyword allows using external libraries (previously installed).
- Import NumPy (aliased as `np`).

In [ ]:

import numpy as np


## 1) Core Concepts: Numpy arrays
- NumPy arrays are **n-dimensional**, **homogeneous** data structures for numerical data.
- Arrays support **vectorized operations**: operations applied to entire arrays without explicit loops.
- **Array programming**: think in terms of whole arrays, not elementwise loops.
- Lots of built-in functions for math, stats, linear algebra, etc.
- Highly optimized for performance (C backend).

### 1.1 Creating arrays
- From Python objects: `np.array([1,2,3])`
- Ranges / grids: `np.arange`, `np.linspace`
- Filled arrays: `np.zeros`, `np.ones`, `np.full`, `np.eye`
- Random: Normal distribution `np.random.normal` (explore others)

In [ ]:

a = np.array([1, 2, 3], dtype=np.int32)
b = np.arange(0, 10, 2)           # step range
c = np.linspace(0, 1, 5)          # 5 points in [0,1]
Z = np.zeros((2,3))
O = np.ones((3,2))
F = np.full((2,2), 7.5)
I = np.eye(3)

R = np.random.normal(low=0, high=10, size=(2,3))
print("a:", a, a.dtype)
print("b:", b)
print("c:", c)
print("Z:", Z)
print("I:", I)
print("R:", R)

### 1.2 Basic Operations
- Elementwise operations: `+ - * / **`


In [ ]:
A = np.array([[1, 2, 3],
     [4, 5, 6]])

print("A:", A, sep="\n")
print("A + 10:", A + 10, sep="\n")
print("A * 2:", A * 2, sep="\n")
print("A ** 2:", A ** 2, sep="\n")  # make a copy to avoid modifying A

B = np.array([[10, 20, 30],
              [40, 50, 60]])

print("A + B:", A + B, sep="\n")
print("A * B:", A * B, sep="\n")


**!Important! tips**:
- 1) assigning parts of an array to another variable does not create a copy, it creates a **view**. Changes to the view will affect the original array. Use `.copy()` or `np.array(A)` to create a true copy.
- 2) Arrays are homogeneous: all elements have the same dtype.
- 3) Using `dtype` parameter when creating arrays ensures the desired data type (optimizes memory and performance).

## 2) Shape, dtype, size

Useful attributes:
- `.shape`: Shape of the array (eg 2x3)
- `.ndim`: Number of dimensions
- `.size`: Number of elements,
- `.dtype`: Type of elements,
- `.itemsize`: Size of elements in Memory
- `astype` to convert dtype

In [ ]:

M = np.random.normal(0, 100, size=(3,4))
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size)
print("dtype:", M.dtype, "| itemsize:", M.itemsize, "bytes")
print("astype float32:", M.astype(np.float32))
print("New itemsize: ", M.astype(np.float32).itemsize, "bytes")

## 3) Indexing & slicing

- 1D arrays indexing and slicing just like lists: `x[i]`, `x[i:j:k]`
- 2D arrays: row/column index/slices: `A[i, j]`, `A[i, j1:j2]`,

In [ ]:

x = np.arange(10)
A = np.random.normal(0, 20, size=(4,5))
print("x:", x)
print("x[2:8:2]:", x[2:8:2])
print("A:", A)
print("A[1, :]:", A[1, :]) # Second row
print("A[:, 2]:", A[:, 2]) # Third column


### 3.1 Boolean masks
Create a boolean mask and use it to filter an array.
- *Boolean mask* is an array of `True`/`False` values.


In [ ]:
# Filter data with boolean mask
print("A greater than 2:", A[A >= 2.0])

# We can store the boolean mask in a variable
mask = (A >= 2.0)
print("mask:", mask.astype(int))
print("A[mask]:", A[mask])

# Peer-Instruction Cards (NumPy Basics)

Predict first, then run the check cell (when provided).

### Card N-1 — Slicing vs copying
```python
A = np.arange(9).reshape(3,3)
B = A[0, :]      # row view or copy?
B[0] = 99
```
**Q:** Does `A` change? Which element?

In [ ]:

A = np.arange(9).reshape(3,3)
B = A[0, :]
print("Before change, A:", A)
print("Before change, B:", B)
B[0] = 99
print("A:", A)  # views: A[0,0] becomes 99

### Card N-2 — Fancy indexing
What is the output of:
```python
X = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(X[1, ::-1])
```


In [ ]:
X = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(X[1, ::-1])

### Card N-3 — Boolean mask
```python
X = np.array([[-1,0,1],[2,-2,3]])
X[X<0] = X[X<0] + 10
```
**Q:** Predict the final `X`.

In [ ]:

X = np.array([[-1,0,1],[2,-2,3]])
X[X<0] = X[X<0] + 10
print(X)

## 4) Broadcasting

Broadcasting allows operations on arrays of different shapes.
**Rules:** align shapes **from the right**; dims are compatible if equal or either is `1`.

Examples: add a vector to each row/column.

In [ ]:

B = np.random.normal(0, 10, size=(3,4))
row = np.array([1, 0, -1, 2])    # row vector shape (4,)
col = np.array([[10],[20],[30]]) # column vector shape (3,1)

print("B:", B)
print("B + row:", B + row)   # broadcast across rows
print("B + col:", B + col)   # broadcast down columns

## 5) Vectorized ops & ufuncs

- Elementwise: `+ - * / **`
- Ufuncs: `np.sqrt`, `np.exp`, `np.clip`, `np.where`
- Aggregations: `np.sum`, `np.mean`, `np.std`,
- `axis=` parameter to specify dimension

In [ ]:

X = np.linspace(-2, 2, 5)
print("X:", X)
print("X**2:", X**2)
print("sqrt(abs(X)):", np.sqrt(np.abs(X)))
print("where(X>=0, 1, -1):", np.where(X>=0, 1, -1))

G = np.random.normal(loc=0, scale=1, size=(3,4))
print("G:", G)
print("sum all:", np.sum(G))
print("mean per column:", np.mean(G, axis=0))
print("std per row:", np.std(G, axis=1))

### Card N-3 — Axis confusion
`np.sum(A, axis=1)` collapses which dimension? Predict result shape for `A.shape == (3,2,3)`.

In [12]:

A = np.random.randint(0, 2, size=(3,2,3))
print(A)
print("sum axis=1 -> shape", np.sum(A, axis=1).shape)
print("sum axis=1 result:", np.sum(A, axis=1))

[[[0 1 0]
  [1 0 0]]

 [[0 0 1]
  [0 0 0]]

 [[0 1 0]
  [1 1 0]]]
sum axis=1 -> shape (3, 3)
sum axis=1 result: [[1 1 0]
 [0 0 1]
 [1 2 0]]


### Card N-4 — Broadcasting addition
Predict the result of:
```python
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
C = A + b
```
What are the shapes of `A`, `b`, and `C`?


In [15]:
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
C = A + b
print("C:", C)

print("Shapes - A:", A.shape, ", b:", b.shape, ", C:", C.shape)

C: [[11 22 33]
 [14 25 36]]
Shapes - A: (2, 3) , b: (3,) , C: (2, 3)


### Card N-5 — Broadcasting shape
Predict the shape of `np.ones((2,1,4)) + np.ones((3,4))` (if valid).

In [13]:

try:
    out = np.ones((2,1,4)) + np.ones((3,4))
    print("ok, shape:", out.shape)
except ValueError as e:
    print("ValueError:", e)

ok, shape: (2, 3, 4)


## Mini challenges
1) Write a Python script to generate a multidimensional array of shape (10,10,1000) where the elements are integer numbers drawn from a discrete uniform distribution in the range [0, 100].


In [ ]:
an_array = np.random.randint(0, 100, size=(10,10,1000))
print("Mini-challenge array shape:", an_array.shape)

2. Write a script to compute the average values of the array of the previous exercise along each dimension, using the function `numpy.mean`.

In [ ]:
average_dim0 = np.mean(an_array, axis=0)
average_dim1 = np.mean(an_array, axis=1)
average_dim2 = np.mean(an_array, axis=2)
print("Average along dim 0 shape:", average_dim0.shape)
print("Average along dim 1 shape:", average_dim1.shape)
print("Average along dim 2 shape:", average_dim2.shape)

3. Given `S` (shape `(m,n)`), subtract the column-wise mean from each column (result same shape).  
```python
S = np.random.normal(size=(4,5))
```

In [ ]:

# Reference solution
S = np.random.normal(size=(4,5))
S_centered = S - S.mean(axis=0, keepdims=True) # keepdims to maintain shape
print("3) centered S shape:", S_centered.shape)


4. Standardize `A` (shape `(m,n)`)  to zero-mean, unit-variance, using broadcasting.
```python
# eg A shape 3,6
A = np.random.normal(loc=2, scale=3, size=(3,6))
```

In [16]:
A = np.random.normal(loc=2, scale=3, size=(3,6))
A_mean = A.mean()
A_std = A.std()
A0 = (A - A_mean) / A_std
print("2) standardized A shape:", A0.shape)

2) row standardized shapes: (3, 6)
